### ISSUE TITLE
Change Wallpaper

### ISSUE THREAD

**Issue by FarukG1** [vincent-lwt/RaspberryCast#88]
Can you make a function to change the "RaspberrryCast is ready" wallpaper. I want to get a nice Wallpaper of a City. I hope you can add the function. Tried to copy a image and change the name to ready.jpg but then it says image not found.

**Comment by mheine** [comment]
Hey! It's probably easier to change the picture yourself, as you mentioned. Make sure that the image is in the `images` folder, and that it's called `ready.jpg`.

Another option is to change the path of the image, and this needs to be done in two places
`    os.system("sudo fbi -T 1 --noverbose -a  images/ready.jpg")` at line 52 in `server.py` and at line 188 in `process.py`.

Feel free to ask for more help if you need it :)
